services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/db/pagila-schema.sql:/docker-entrypoint-initdb.d/1-pagila-schema.sql
      - ./data/db/pagila-data.sql:/docker-entrypoint-initdb.d/2-pagila-data.sql
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

volumes:
  pgdata: